### ISSUE TITLE
all_link.c has 7 errors when trying to build

### ISSUE THREAD

**Issue by matositai** [nettoyeurny/libpd_link_sample#1]
Here are the problematic lives:
ABLLinkProposeTempo(libpdLinkRef, x->tempo, libpd_curr_time);
ABLLinkSetQuantum(libpdLinkRef, x->quantum);
curr_beat_time = ABLLinkResetBeatTime(libpdLinkRef, x->prev_beat_time, libpd_curr_time);
curr_beat_time = ABLLinkBeatTimeAtHostTime(libpdLinkRef, libpd_curr_time);
double quantum = ABLLinkGetQuantum(libpdLinkRef);
double curr_phase = ABLLinkPhase(libpdLinkRef, curr_beat_time, quantum);
outlet_float(x->tempo_out, ABLLinkGetSessionTempo(libpdLinkRef));

**Comment by matositai** [comment]
This is caused when attempting to integrate with Link 2.0.0

**Comment by nettoyeurny** [comment]
True. I've been meaning to update to Link 2.0.0 but haven't gotten around to it yet. I'll look into this now.

**Comment by matositai** [comment]
Hi Peter,
I was able to build once I referred to link 1.0.3
I wonder how they’ll apply backward compatibility.
Let me know if I can help with anything…
Thanks,
Matos

**Comment by brs-ableton** [comment]
There is a break in API compatibility between LinkKit 1.x and LinkKit 2.x (as the major version increment is intended to indicate). But just so there's no confusion, applications built against LinkKit 1.x are compatible on the wire with those built with LinkKit 2.x, so they will work fine in a session together.

**Comment by nettoyeurny** [comment]
Hi Brent, quick question about LinkKit 2.x. Suppose I call ABLLinkRequestBeatAtTime and then I immediately call ABLLinkBeatAtTime (same local time line, same hostTimeAtOutput). What beat time should I expect to get? In other words, does the remapping take effect right away?

**Comment by brs-ableton** [comment]
Hi Peter - Yes the remapping should be immediately visible on the timeline, but you might not get the exact beat time back that you specified if you're in a session with other participants. In that case `ABLLinkRequestBeatAtTime` will do the closest re-mapping to what was requested that preserves phase.

Are you seeing something different?

**Comment by nettoyeurny** [comment]
Thanks, Brent! I hadn't actually tried this yet when I asked. Now that I've revised the entire Link external using LinkKit 2.0.0, I'm happy to confirm that it behaves just like you described.

If you're interested in the latest version, you can find it in the new link2_0_0 branches of this sample app and the pd_link_bridge project.
